version: '3.7'

services:
  client-app:
    build:
      context: ./

    volumes:
      - .:/home/app/
      - ./node_modules/:/home/app/node_modules/

    ports:
      - 3000:3000

    restart: unless-stopped
